name: daily-cron
on:
  schedule:
    - cron: "* * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Currency Conversion API Route
        run: |
          curl --request POST \
          --url 'smartrr-sr-app-engineer-homework-ldp1i1k1g-erockdotdev.vercel.app/api/currency-converter'
